// flow-typed signature: 226cc1b130888e62894aae4dbf8aef45
// flow-typed version: <<STUB>>/bit-js_v^0.2.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bit-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'bit-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bit-js/dist/bit-id/bit-id' {
  declare module.exports: any;
}

declare module 'bit-js/dist/bit-id/find-latest-version' {
  declare module.exports: any;
}

declare module 'bit-js/dist/bit-id/parse-bit-full-id' {
  declare module.exports: any;
}

declare module 'bit-js/dist/bit-id/parse-bit-inline-id' {
  declare module.exports: any;
}

declare module 'bit-js/dist/bit-json/bit-json' {
  declare module.exports: any;
}

declare module 'bit-js/dist/bit-json/index' {
  declare module.exports: any;
}

declare module 'bit-js/dist/bit-locators/assume-only-one-locator' {
  declare module.exports: any;
}

declare module 'bit-js/dist/bit-locators/bit-json-locator' {
  declare module.exports: any;
}

declare module 'bit-js/dist/bit-resolver/bit-resolver' {
  declare module.exports: any;
}

declare module 'bit-js/dist/bit-resolver/index' {
  declare module.exports: any;
}

declare module 'bit-js/dist/bit-resolver/resolve-from-full-id' {
  declare module.exports: any;
}

declare module 'bit-js/dist/bit/bit-utils' {
  declare module.exports: any;
}

declare module 'bit-js/dist/bit/bit' {
  declare module.exports: any;
}

declare module 'bit-js/dist/bit/load-bit' {
  declare module.exports: any;
}

declare module 'bit-js/dist/bit/load-impl' {
  declare module.exports: any;
}

declare module 'bit-js/dist/bit/load-local-bit-json' {
  declare module.exports: any;
}

declare module 'bit-js/dist/compilers/bit-resolver' {
  declare module.exports: any;
}

declare module 'bit-js/dist/compilers/load-compiler' {
  declare module.exports: any;
}

declare module 'bit-js/dist/constants' {
  declare module.exports: any;
}

declare module 'bit-js/dist/consumer/consumer-utils' {
  declare module.exports: any;
}

declare module 'bit-js/dist/consumer/consumer' {
  declare module.exports: any;
}

declare module 'bit-js/dist/consumer/locate-bit-environment' {
  declare module.exports: any;
}

declare module 'bit-js/dist/consumer/locate-bits-directory' {
  declare module.exports: any;
}

declare module 'bit-js/dist/consumer/locate-consumer' {
  declare module.exports: any;
}

declare module 'bit-js/dist/dependency-map/dependency-map' {
  declare module.exports: any;
}

declare module 'bit-js/dist/dependency-map/index' {
  declare module.exports: any;
}

declare module 'bit-js/dist/dependencyMap/dependency-map' {
  declare module.exports: any;
}

declare module 'bit-js/dist/dependencyMap/index' {
  declare module.exports: any;
}

declare module 'bit-js/dist/exceptions/bit-not-exists' {
  declare module.exports: any;
}

declare module 'bit-js/dist/exceptions/component-not-exists-in' {
  declare module.exports: any;
}

declare module 'bit-js/dist/exceptions/component-not-exists.1' {
  declare module.exports: any;
}

declare module 'bit-js/dist/exceptions/component-not-exists' {
  declare module.exports: any;
}

declare module 'bit-js/dist/exceptions/index' {
  declare module.exports: any;
}

declare module 'bit-js/dist/exceptions/invalid-bit-json' {
  declare module.exports: any;
}

declare module 'bit-js/dist/exceptions/invalid-component-id' {
  declare module.exports: any;
}

declare module 'bit-js/dist/exceptions/invalid-version' {
  declare module.exports: any;
}

declare module 'bit-js/dist/exceptions/multiple-scopes-no-def' {
  declare module.exports: any;
}

declare module 'bit-js/dist/exceptions/no-consumer-found' {
  declare module.exports: any;
}

declare module 'bit-js/dist/exceptions/no-single-component-inline' {
  declare module.exports: any;
}

declare module 'bit-js/dist/exceptions/version-not-exists' {
  declare module.exports: any;
}

declare module 'bit-js/dist/index' {
  declare module.exports: any;
}

declare module 'bit-js/dist/repo/locate-repo' {
  declare module.exports: any;
}

declare module 'bit-js/dist/repo/repo-utils' {
  declare module.exports: any;
}

declare module 'bit-js/dist/strategies/index' {
  declare module.exports: any;
}

declare module 'bit-js/dist/strategies/load-bit-assuming-one-scope-one-version' {
  declare module.exports: any;
}

declare module 'bit-js/dist/strategies/load-bit-assuming-only-one' {
  declare module.exports: any;
}

declare module 'bit-js/dist/strategies/load-bit-inline' {
  declare module.exports: any;
}

declare module 'bit-js/dist/strategies/load-bit-multiple-scopes' {
  declare module.exports: any;
}

declare module 'bit-js/dist/strategies/load-bit-using-bit-jsons' {
  declare module.exports: any;
}

declare module 'bit-js/dist/strategies/load-bit-using-dependecies-map' {
  declare module.exports: any;
}

declare module 'bit-js/dist/strategies/load-latest-bit-assuming-one-scope' {
  declare module.exports: any;
}

declare module 'bit-js/dist/transpilers/load-transpiler' {
  declare module.exports: any;
}

declare module 'bit-js/gulpfile' {
  declare module.exports: any;
}

declare module 'bit-js/resources/impl.template' {
  declare module.exports: any;
}

declare module 'bit-js/resources/specs.template' {
  declare module.exports: any;
}

declare module 'bit-js/src/bit-id/find-latest-version' {
  declare module.exports: any;
}

declare module 'bit-js/src/bit-id/parse-bit-full-id' {
  declare module.exports: any;
}

declare module 'bit-js/src/bit-id/parse-bit-inline-id' {
  declare module.exports: any;
}

declare module 'bit-js/src/bit-json/bit-json' {
  declare module.exports: any;
}

declare module 'bit-js/src/bit-json/index' {
  declare module.exports: any;
}

declare module 'bit-js/src/bit-resolver/bit-resolver' {
  declare module.exports: any;
}

declare module 'bit-js/src/bit-resolver/index' {
  declare module.exports: any;
}

declare module 'bit-js/src/bit-resolver/resolve-from-full-id' {
  declare module.exports: any;
}

declare module 'bit-js/src/bit/bit' {
  declare module.exports: any;
}

declare module 'bit-js/src/constants' {
  declare module.exports: any;
}

declare module 'bit-js/src/consumer/consumer-utils' {
  declare module.exports: any;
}

declare module 'bit-js/src/consumer/consumer' {
  declare module.exports: any;
}

declare module 'bit-js/src/consumer/locate-bit-environment' {
  declare module.exports: any;
}

declare module 'bit-js/src/dependency-map/dependency-map' {
  declare module.exports: any;
}

declare module 'bit-js/src/dependency-map/index' {
  declare module.exports: any;
}

declare module 'bit-js/src/exceptions/component-not-exists-in' {
  declare module.exports: any;
}

declare module 'bit-js/src/exceptions/component-not-exists' {
  declare module.exports: any;
}

declare module 'bit-js/src/exceptions/index' {
  declare module.exports: any;
}

declare module 'bit-js/src/exceptions/invalid-bit-json' {
  declare module.exports: any;
}

declare module 'bit-js/src/exceptions/invalid-component-id' {
  declare module.exports: any;
}

declare module 'bit-js/src/exceptions/invalid-version' {
  declare module.exports: any;
}

declare module 'bit-js/src/exceptions/multiple-scopes-no-def' {
  declare module.exports: any;
}

declare module 'bit-js/src/exceptions/no-consumer-found' {
  declare module.exports: any;
}

declare module 'bit-js/src/exceptions/version-not-exists' {
  declare module.exports: any;
}

declare module 'bit-js/src/index' {
  declare module.exports: any;
}

declare module 'bit-js/src/strategies/index' {
  declare module.exports: any;
}

declare module 'bit-js/src/strategies/load-bit-assuming-one-scope-one-version' {
  declare module.exports: any;
}

declare module 'bit-js/src/strategies/load-bit-inline' {
  declare module.exports: any;
}

declare module 'bit-js/src/strategies/load-bit-multiple-scopes' {
  declare module.exports: any;
}

declare module 'bit-js/src/strategies/load-bit-using-bit-jsons' {
  declare module.exports: any;
}

declare module 'bit-js/src/strategies/load-latest-bit-assuming-one-scope' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bit-js/dist/bit-id/bit-id.js' {
  declare module.exports: $Exports<'bit-js/dist/bit-id/bit-id'>;
}
declare module 'bit-js/dist/bit-id/find-latest-version.js' {
  declare module.exports: $Exports<'bit-js/dist/bit-id/find-latest-version'>;
}
declare module 'bit-js/dist/bit-id/parse-bit-full-id.js' {
  declare module.exports: $Exports<'bit-js/dist/bit-id/parse-bit-full-id'>;
}
declare module 'bit-js/dist/bit-id/parse-bit-inline-id.js' {
  declare module.exports: $Exports<'bit-js/dist/bit-id/parse-bit-inline-id'>;
}
declare module 'bit-js/dist/bit-json/bit-json.js' {
  declare module.exports: $Exports<'bit-js/dist/bit-json/bit-json'>;
}
declare module 'bit-js/dist/bit-json/index.js' {
  declare module.exports: $Exports<'bit-js/dist/bit-json/index'>;
}
declare module 'bit-js/dist/bit-locators/assume-only-one-locator.js' {
  declare module.exports: $Exports<'bit-js/dist/bit-locators/assume-only-one-locator'>;
}
declare module 'bit-js/dist/bit-locators/bit-json-locator.js' {
  declare module.exports: $Exports<'bit-js/dist/bit-locators/bit-json-locator'>;
}
declare module 'bit-js/dist/bit-resolver/bit-resolver.js' {
  declare module.exports: $Exports<'bit-js/dist/bit-resolver/bit-resolver'>;
}
declare module 'bit-js/dist/bit-resolver/index.js' {
  declare module.exports: $Exports<'bit-js/dist/bit-resolver/index'>;
}
declare module 'bit-js/dist/bit-resolver/resolve-from-full-id.js' {
  declare module.exports: $Exports<'bit-js/dist/bit-resolver/resolve-from-full-id'>;
}
declare module 'bit-js/dist/bit/bit-utils.js' {
  declare module.exports: $Exports<'bit-js/dist/bit/bit-utils'>;
}
declare module 'bit-js/dist/bit/bit.js' {
  declare module.exports: $Exports<'bit-js/dist/bit/bit'>;
}
declare module 'bit-js/dist/bit/load-bit.js' {
  declare module.exports: $Exports<'bit-js/dist/bit/load-bit'>;
}
declare module 'bit-js/dist/bit/load-impl.js' {
  declare module.exports: $Exports<'bit-js/dist/bit/load-impl'>;
}
declare module 'bit-js/dist/bit/load-local-bit-json.js' {
  declare module.exports: $Exports<'bit-js/dist/bit/load-local-bit-json'>;
}
declare module 'bit-js/dist/compilers/bit-resolver.js' {
  declare module.exports: $Exports<'bit-js/dist/compilers/bit-resolver'>;
}
declare module 'bit-js/dist/compilers/load-compiler.js' {
  declare module.exports: $Exports<'bit-js/dist/compilers/load-compiler'>;
}
declare module 'bit-js/dist/constants.js' {
  declare module.exports: $Exports<'bit-js/dist/constants'>;
}
declare module 'bit-js/dist/consumer/consumer-utils.js' {
  declare module.exports: $Exports<'bit-js/dist/consumer/consumer-utils'>;
}
declare module 'bit-js/dist/consumer/consumer.js' {
  declare module.exports: $Exports<'bit-js/dist/consumer/consumer'>;
}
declare module 'bit-js/dist/consumer/locate-bit-environment.js' {
  declare module.exports: $Exports<'bit-js/dist/consumer/locate-bit-environment'>;
}
declare module 'bit-js/dist/consumer/locate-bits-directory.js' {
  declare module.exports: $Exports<'bit-js/dist/consumer/locate-bits-directory'>;
}
declare module 'bit-js/dist/consumer/locate-consumer.js' {
  declare module.exports: $Exports<'bit-js/dist/consumer/locate-consumer'>;
}
declare module 'bit-js/dist/dependency-map/dependency-map.js' {
  declare module.exports: $Exports<'bit-js/dist/dependency-map/dependency-map'>;
}
declare module 'bit-js/dist/dependency-map/index.js' {
  declare module.exports: $Exports<'bit-js/dist/dependency-map/index'>;
}
declare module 'bit-js/dist/dependencyMap/dependency-map.js' {
  declare module.exports: $Exports<'bit-js/dist/dependencyMap/dependency-map'>;
}
declare module 'bit-js/dist/dependencyMap/index.js' {
  declare module.exports: $Exports<'bit-js/dist/dependencyMap/index'>;
}
declare module 'bit-js/dist/exceptions/bit-not-exists.js' {
  declare module.exports: $Exports<'bit-js/dist/exceptions/bit-not-exists'>;
}
declare module 'bit-js/dist/exceptions/component-not-exists-in.js' {
  declare module.exports: $Exports<'bit-js/dist/exceptions/component-not-exists-in'>;
}
declare module 'bit-js/dist/exceptions/component-not-exists.1.js' {
  declare module.exports: $Exports<'bit-js/dist/exceptions/component-not-exists.1'>;
}
declare module 'bit-js/dist/exceptions/component-not-exists.js' {
  declare module.exports: $Exports<'bit-js/dist/exceptions/component-not-exists'>;
}
declare module 'bit-js/dist/exceptions/index.js' {
  declare module.exports: $Exports<'bit-js/dist/exceptions/index'>;
}
declare module 'bit-js/dist/exceptions/invalid-bit-json.js' {
  declare module.exports: $Exports<'bit-js/dist/exceptions/invalid-bit-json'>;
}
declare module 'bit-js/dist/exceptions/invalid-component-id.js' {
  declare module.exports: $Exports<'bit-js/dist/exceptions/invalid-component-id'>;
}
declare module 'bit-js/dist/exceptions/invalid-version.js' {
  declare module.exports: $Exports<'bit-js/dist/exceptions/invalid-version'>;
}
declare module 'bit-js/dist/exceptions/multiple-scopes-no-def.js' {
  declare module.exports: $Exports<'bit-js/dist/exceptions/multiple-scopes-no-def'>;
}
declare module 'bit-js/dist/exceptions/no-consumer-found.js' {
  declare module.exports: $Exports<'bit-js/dist/exceptions/no-consumer-found'>;
}
declare module 'bit-js/dist/exceptions/no-single-component-inline.js' {
  declare module.exports: $Exports<'bit-js/dist/exceptions/no-single-component-inline'>;
}
declare module 'bit-js/dist/exceptions/version-not-exists.js' {
  declare module.exports: $Exports<'bit-js/dist/exceptions/version-not-exists'>;
}
declare module 'bit-js/dist/index.js' {
  declare module.exports: $Exports<'bit-js/dist/index'>;
}
declare module 'bit-js/dist/repo/locate-repo.js' {
  declare module.exports: $Exports<'bit-js/dist/repo/locate-repo'>;
}
declare module 'bit-js/dist/repo/repo-utils.js' {
  declare module.exports: $Exports<'bit-js/dist/repo/repo-utils'>;
}
declare module 'bit-js/dist/strategies/index.js' {
  declare module.exports: $Exports<'bit-js/dist/strategies/index'>;
}
declare module 'bit-js/dist/strategies/load-bit-assuming-one-scope-one-version.js' {
  declare module.exports: $Exports<'bit-js/dist/strategies/load-bit-assuming-one-scope-one-version'>;
}
declare module 'bit-js/dist/strategies/load-bit-assuming-only-one.js' {
  declare module.exports: $Exports<'bit-js/dist/strategies/load-bit-assuming-only-one'>;
}
declare module 'bit-js/dist/strategies/load-bit-inline.js' {
  declare module.exports: $Exports<'bit-js/dist/strategies/load-bit-inline'>;
}
declare module 'bit-js/dist/strategies/load-bit-multiple-scopes.js' {
  declare module.exports: $Exports<'bit-js/dist/strategies/load-bit-multiple-scopes'>;
}
declare module 'bit-js/dist/strategies/load-bit-using-bit-jsons.js' {
  declare module.exports: $Exports<'bit-js/dist/strategies/load-bit-using-bit-jsons'>;
}
declare module 'bit-js/dist/strategies/load-bit-using-dependecies-map.js' {
  declare module.exports: $Exports<'bit-js/dist/strategies/load-bit-using-dependecies-map'>;
}
declare module 'bit-js/dist/strategies/load-latest-bit-assuming-one-scope.js' {
  declare module.exports: $Exports<'bit-js/dist/strategies/load-latest-bit-assuming-one-scope'>;
}
declare module 'bit-js/dist/transpilers/load-transpiler.js' {
  declare module.exports: $Exports<'bit-js/dist/transpilers/load-transpiler'>;
}
declare module 'bit-js/gulpfile.js' {
  declare module.exports: $Exports<'bit-js/gulpfile'>;
}
declare module 'bit-js/resources/impl.template.js' {
  declare module.exports: $Exports<'bit-js/resources/impl.template'>;
}
declare module 'bit-js/resources/specs.template.js' {
  declare module.exports: $Exports<'bit-js/resources/specs.template'>;
}
declare module 'bit-js/src/bit-id/find-latest-version.js' {
  declare module.exports: $Exports<'bit-js/src/bit-id/find-latest-version'>;
}
declare module 'bit-js/src/bit-id/parse-bit-full-id.js' {
  declare module.exports: $Exports<'bit-js/src/bit-id/parse-bit-full-id'>;
}
declare module 'bit-js/src/bit-id/parse-bit-inline-id.js' {
  declare module.exports: $Exports<'bit-js/src/bit-id/parse-bit-inline-id'>;
}
declare module 'bit-js/src/bit-json/bit-json.js' {
  declare module.exports: $Exports<'bit-js/src/bit-json/bit-json'>;
}
declare module 'bit-js/src/bit-json/index.js' {
  declare module.exports: $Exports<'bit-js/src/bit-json/index'>;
}
declare module 'bit-js/src/bit-resolver/bit-resolver.js' {
  declare module.exports: $Exports<'bit-js/src/bit-resolver/bit-resolver'>;
}
declare module 'bit-js/src/bit-resolver/index.js' {
  declare module.exports: $Exports<'bit-js/src/bit-resolver/index'>;
}
declare module 'bit-js/src/bit-resolver/resolve-from-full-id.js' {
  declare module.exports: $Exports<'bit-js/src/bit-resolver/resolve-from-full-id'>;
}
declare module 'bit-js/src/bit/bit.js' {
  declare module.exports: $Exports<'bit-js/src/bit/bit'>;
}
declare module 'bit-js/src/constants.js' {
  declare module.exports: $Exports<'bit-js/src/constants'>;
}
declare module 'bit-js/src/consumer/consumer-utils.js' {
  declare module.exports: $Exports<'bit-js/src/consumer/consumer-utils'>;
}
declare module 'bit-js/src/consumer/consumer.js' {
  declare module.exports: $Exports<'bit-js/src/consumer/consumer'>;
}
declare module 'bit-js/src/consumer/locate-bit-environment.js' {
  declare module.exports: $Exports<'bit-js/src/consumer/locate-bit-environment'>;
}
declare module 'bit-js/src/dependency-map/dependency-map.js' {
  declare module.exports: $Exports<'bit-js/src/dependency-map/dependency-map'>;
}
declare module 'bit-js/src/dependency-map/index.js' {
  declare module.exports: $Exports<'bit-js/src/dependency-map/index'>;
}
declare module 'bit-js/src/exceptions/component-not-exists-in.js' {
  declare module.exports: $Exports<'bit-js/src/exceptions/component-not-exists-in'>;
}
declare module 'bit-js/src/exceptions/component-not-exists.js' {
  declare module.exports: $Exports<'bit-js/src/exceptions/component-not-exists'>;
}
declare module 'bit-js/src/exceptions/index.js' {
  declare module.exports: $Exports<'bit-js/src/exceptions/index'>;
}
declare module 'bit-js/src/exceptions/invalid-bit-json.js' {
  declare module.exports: $Exports<'bit-js/src/exceptions/invalid-bit-json'>;
}
declare module 'bit-js/src/exceptions/invalid-component-id.js' {
  declare module.exports: $Exports<'bit-js/src/exceptions/invalid-component-id'>;
}
declare module 'bit-js/src/exceptions/invalid-version.js' {
  declare module.exports: $Exports<'bit-js/src/exceptions/invalid-version'>;
}
declare module 'bit-js/src/exceptions/multiple-scopes-no-def.js' {
  declare module.exports: $Exports<'bit-js/src/exceptions/multiple-scopes-no-def'>;
}
declare module 'bit-js/src/exceptions/no-consumer-found.js' {
  declare module.exports: $Exports<'bit-js/src/exceptions/no-consumer-found'>;
}
declare module 'bit-js/src/exceptions/version-not-exists.js' {
  declare module.exports: $Exports<'bit-js/src/exceptions/version-not-exists'>;
}
declare module 'bit-js/src/index.js' {
  declare module.exports: $Exports<'bit-js/src/index'>;
}
declare module 'bit-js/src/strategies/index.js' {
  declare module.exports: $Exports<'bit-js/src/strategies/index'>;
}
declare module 'bit-js/src/strategies/load-bit-assuming-one-scope-one-version.js' {
  declare module.exports: $Exports<'bit-js/src/strategies/load-bit-assuming-one-scope-one-version'>;
}
declare module 'bit-js/src/strategies/load-bit-inline.js' {
  declare module.exports: $Exports<'bit-js/src/strategies/load-bit-inline'>;
}
declare module 'bit-js/src/strategies/load-bit-multiple-scopes.js' {
  declare module.exports: $Exports<'bit-js/src/strategies/load-bit-multiple-scopes'>;
}
declare module 'bit-js/src/strategies/load-bit-using-bit-jsons.js' {
  declare module.exports: $Exports<'bit-js/src/strategies/load-bit-using-bit-jsons'>;
}
declare module 'bit-js/src/strategies/load-latest-bit-assuming-one-scope.js' {
  declare module.exports: $Exports<'bit-js/src/strategies/load-latest-bit-assuming-one-scope'>;
}
