// flow-typed signature: 4827441820408365668be1f3ed5cfa06
// flow-typed version: <<STUB>>/sequest_v^0.9.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sequest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'sequest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sequest/connection' {
  declare module.exports: any;
}

declare module 'sequest/test/test-basic' {
  declare module.exports: any;
}

declare module 'sequest/test/test-get-put-connect' {
  declare module.exports: any;
}

declare module 'sequest/test/test-get-put' {
  declare module.exports: any;
}

declare module 'sequest/test/test-stream-connect' {
  declare module.exports: any;
}

declare module 'sequest/test/test-stream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sequest/connection.js' {
  declare module.exports: $Exports<'sequest/connection'>;
}
declare module 'sequest/index' {
  declare module.exports: $Exports<'sequest'>;
}
declare module 'sequest/index.js' {
  declare module.exports: $Exports<'sequest'>;
}
declare module 'sequest/test/test-basic.js' {
  declare module.exports: $Exports<'sequest/test/test-basic'>;
}
declare module 'sequest/test/test-get-put-connect.js' {
  declare module.exports: $Exports<'sequest/test/test-get-put-connect'>;
}
declare module 'sequest/test/test-get-put.js' {
  declare module.exports: $Exports<'sequest/test/test-get-put'>;
}
declare module 'sequest/test/test-stream-connect.js' {
  declare module.exports: $Exports<'sequest/test/test-stream-connect'>;
}
declare module 'sequest/test/test-stream.js' {
  declare module.exports: $Exports<'sequest/test/test-stream'>;
}
